### ISSUE TITLE
版本 16.2.3(简体中文)新版本不支持，注册机版本v16.0.7.0+

### ISSUE THREAD

**Issue by Lvbuqing** [LiJunYi2/navicat-keygen-16V#10]
![微信截图_20230629110410](https://github.com/LiJunYi2/navicat-keygen-16V/assets/32841009/1161f01c-cb61-4321-8cd5-4ffc0c391351)
![微信图片_20230629110206](https://github.com/LiJunYi2/navicat-keygen-16V/assets/32841009/16fddaba-26a4-4306-8b56-cc0ea7235a78)

**Comment by LiJunYi2** [comment]
16.2.x 暂时无法激活，先使用16.1.x版本，等新版本激活出来会更新的。

**Comment by Lvbuqing** [comment]
大佬辛苦了

**Comment by gaohong527** [comment]
等待大佬

**Comment by gaohong527** [comment]
辛苦大佬了

**Comment by ming0804** [comment]
辛苦大佬

**Comment by 1273082756** [comment]
辛苦大佬, 坐等16.2

**Comment by yearspark** [comment]
辛苦大佬, 坐等16.2

**Comment by hanxiang-li** [comment]
替换dll是成功了
