### ISSUE TITLE
mac Navicat16.2

### ISSUE THREAD

**Issue by jlcczhangcong** [LiJunYi2/navicat-keygen-16V#13]
mac Navicat16.2 有破解版本吗

**Comment by LiJunYi2** [comment]
> mac Navicat16.2 有破解版本吗

Mac暂无，mac要从xclient官网获取了，目前还没有16.2.x版本的

**Comment by jlcczhangcong** [comment]
好的。感谢
| |
jlcczhangcong
|
|
***@***.***
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 07/12/2023 19:33 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [LiJunYi2/navicat-keygen-16V] mac Navicat16.2 (Issue #13) |

mac Navicat16.2 有破解版本吗

Mac暂无，mac要从xclient官网获取了，目前还没有16.2.x版本的
