### ISSUE TITLE
win10 navicat16.2.6, 点击patch报错

### ISSUE THREAD

**Issue by ifYouLike-Weirdo** [LiJunYi2/navicat-keygen-16V#15]
![image](https://github.com/LiJunYi2/navicat-keygen-16V/assets/55228333/eace02ae-4f9e-400e-a1eb-852bf944fc24)

**Comment by LiJunYi2** [comment]
16.2.x版本请看[releases-v16.2.3](https://github.com/LiJunYi2/navicat-keygen-16V/releases/tag/v16.2.3)

**Comment by ifYouLike-Weirdo** [comment]
> 16.2.x版本请看[releases-v16.2.3](https://github.com/LiJunYi2/navicat-keygen-16V/releases/tag/v16.2.3)

.bat文件双击点不开

**Comment by ifYouLike-Weirdo** [comment]
> 16.2.x版本请看[releases-v16.2.3](https://github.com/LiJunYi2/navicat-keygen-16V/releases/tag/v16.2.3)

.bat点击闪退。。

**Comment by ifYouLike-Weirdo** [comment]
感谢大佬！！
