### ISSUE TITLE
16.2.x版本的无限重置试用bat

### ISSUE THREAD

**Issue by LiJunYi2** [LiJunYi2/navicat-keygen-16V#16]
16.2.x版本重置试用bat 脚本（**16.3.x失效**）：
```shell
echo Delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Update
reg delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Update /f
echo Delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Registration[version and language]
for /f %%i in ('"REG QUERY "HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium" /s | findstr /L Registration"') do (
    reg delete %%i /va /f
)

echo Delete Info and ShellFolder under HKEY_CURRENT_USER\Software\Classes\CLSID
for /f "tokens=*" %%a in ('reg query "HKEY_CURRENT_USER\Software\Classes\CLSID"') do (
  for /f "tokens=*" %%l in ('reg query "%%a" /f "Info" /s /e ^| findstr /i "Info"') do (
    echo Delete: %%a
    reg delete %%a /f
  )
  for /f "tokens=*" %%l in ('reg query "%%a" /f "ShellFolder" /s /e ^| findstr /i "ShellFolder"') do (
    echo Delete: %%a
    reg delete %%a /f
  )
)
```

脚本来源：[lyc8503](https://github.com/lyc8503)

**Comment by tonyeeup** [comment]
在这个bat最后面加一行，
start /d "C:\Program Files\PremiumSoft\Navicat Premium 16" navicat.exe
然后把系统菜单里 navicat 快捷方式属性里面的指向改成这个bat文件，每次启动就先重置试用，不用加定时任务。

**Comment by LiJunYi2** [comment]
> 在这个bat最后面加一行， start /d "C:\Program Files\PremiumSoft\Navicat Premium 16" navicat.exe 然后把系统菜单里 navicat 快捷方式属性里面的指向改成这个bat文件，每次启动就先重置试用，不用加定时任务。

哈哈哈哈，这办法妙啊😂😂😂

**Comment by mrmyn** [comment]
IDM文章和谐了

**Comment by LiJunYi2** [comment]
> IDM文章和谐了

Idm文章地址已更新🫡

**Comment by yueyangyang** [comment]
16.3.x失效了

**Comment by LiJunYi2** [comment]
> 16.3.x失效了

那就用 `dll` 文件吧或者降版本

**Comment by rainerosion** [comment]
> 16.3.x失效了
我用的这个目前再用的版本16.3.2有效
```bat
@echo off
set dn=Info
set dn2=ShellFolder
set rp=HKEY_CURRENT_USER\Software\Classes\CLSID
:: reg delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Registration14XCS /f  %针对<strong><font color="#FF0000">navicat</font></strong>15%
reg delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Registration16XCS /f
reg delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Update /f
echo finding.....
for /f "tokens=*" %%a in ('reg query "%rp%"') do (
 echo %%a
for /f "tokens=*" %%l in ('reg query "%%a" /f "%dn%" /s /e ^|findstr /i "%dn%"') do (
  echo deleteing: %%a
  reg delete %%a /f
)
for /f "tokens=*" %%l in ('reg query "%%a" /f "%dn2%" /s /e ^|findstr /i "%dn2%"') do (
  echo deleteing: %%a
  reg delete %%a /f
)
)
echo re trial done!
  
pause
exit
```

**Comment by LiJunYi2** [comment]
> > 16.3.x失效了
> > 我用的这个目前再用的版本16.3.2有效
> 
> ```batchfile
> @echo off
> set dn=Info
> set dn2=ShellFolder
> set rp=HKEY_CURRENT_USER\Software\Classes\CLSID
> :: reg delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Registration14XCS /f  %针对<strong><font color="#FF0000">navicat</font></strong>15%
> reg delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Registration16XCS /f
> reg delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Update /f
> echo finding.....
> for /f "tokens=*" %%a in ('reg query "%rp%"') do (
>  echo %%a
> for /f "tokens=*" %%l in ('reg query "%%a" /f "%dn%" /s /e ^|findstr /i "%dn%"') do (
>   echo deleteing: %%a
>   reg delete %%a /f
> )
> for /f "tokens=*" %%l in ('reg query "%%a" /f "%dn2%" /s /e ^|findstr /i "%dn2%"') do (
>   echo deleteing: %%a
>   reg delete %%a /f
> )
> )
> echo re trial done!
>   
> pause
> exit
> ```

ok👌🏻
