### ISSUE TITLE
MAC AppStore 版本16.1.0-16.3.3版本通杀

### ISSUE THREAD

**Issue by LiJunYi2** [LiJunYi2/navicat-keygen-16V#17]
## Navicat Premium Crack 

https://www.aliyundrive.com/s/Qba3H9pHpzQ
提取码: s51p

**夸克盘链接**
链接：https://pan.quark.cn/s/f48fe6b5c43a
提取码：1qhu

## xclient 16.3.2版本
**部分设备无法使用，那就试试 xclient 上的：16.3.2 版本**
https://www.123pan.com/s/YheEjv-6P1Xv.html
提取码:2vO3

**常见问题**
一、提示已损坏无法打开解决办法：

1、打开终端；
2、输入以下命令，回车；
`sudo xattr -d com.apple.quarantine /Applications/xxxx.app`

注意：`/Applications/xxxx.app` 换成你的App路径（推荐直接将.app文件拖入终端中自动生成路径，以防空格等转义字符手动复制或输入出现错误）
3、重启App即可。

## Navicat Premium Crack使用教程
1、请记得先备份数据！！！
2、从 `MAC` 的 `App Store`下载`Navicat Premium`后就不要打开`Navicat Premium`！！！运行激活工具前务必关闭`Navicat Premium`！！

## 出处
`Navicat Premium Crack`为`MacApp`分享频道全网首发！通杀`16.1.0`及以后的`Mac App Store`版本！

## 本人设备
MacBook Pro + M2 + Sonoma 14.1。目前正常使用。部分设备如果无法使用，请使用上方 xclient 上的安装包。

![navicat16 3 2](https://github.com/LiJunYi2/navicat-keygen-16V/assets/40384503/7b291b98-09ed-49a7-a8f4-9fa90fd0e278)

**Comment by easylolicon** [comment]
Navicat Premium Crack 这个文件怎么用。mac默认打不开，如何执行

**Comment by LiJunYi2** [comment]
> Navicat Premium Crack 这个文件怎么用。mac默认打不开，如何执行

我这就直接解压后，双击运行 dmg 文件就行了。打不开有提示什么吗？M1?

**Comment by easylolicon** [comment]
下载后 是个 rar压缩包 <img width="116" alt="image" src="https://github.com/LiJunYi2/navicat-keygen-16V/assets/32192838/bcb8bd0a-6c16-4e04-9d38-6c44d8ff1f5f">

**Comment by LiJunYi2** [comment]
> 下载后 是个 rar压缩包 <img alt="image" width="116" src="https://user-images.githubusercontent.com/32192838/280584351-bcb8bd0a-6c16-4e04-9d38-6c44d8ff1f5f.png">
> 
> 解压后 <img alt="image" width="554" src="https://user-images.githubusercontent.com/32192838/280584479-7b79b7a2-97d8-47c5-9431-2745dfac3022.png">
> 
> 无后缀文件。无法执行。添加.dmg 显示文件损坏也不行
> 
> cpu是m1pro

我刚去试了下，下载完后解压正常显示dmg格式。你从这下载吧，刚上传了 dmg 文件：
https://t.wss.pet/f/clmq7aspfws

**Comment by easylolicon** [comment]
> > 下载后 是个 rar压缩包 <img alt="image" width="116" src="https://user-images.githubusercontent.com/32192838/280584351-bcb8bd0a-6c16-4e04-9d38-6c44d8ff1f5f.png">
> > 解压后 <img alt="image" width="554" src="https://user-images.githubusercontent.com/32192838/280584479-7b79b7a2-97d8-47c5-9431-2745dfac3022.png">
> > 无后缀文件。无法执行。添加.dmg 显示文件损坏也不行
> > cpu是m1pro
> 
> 我刚去试了下，下载完后解压正常显示dmg格式。你从这下载吧，刚上传了 dmg 文件： https://t.wss.pet/f/clmq7aspfws

可以了。谢谢

**Comment by h0352** [comment]
楼主，idea无法更新了

**Comment by h0352** [comment]
楼主。idea破解文章无了，有别的地址吗

**Comment by LiJunYi2** [comment]
> 楼主。idea破解文章无了，有别的地址吗

来啦来啦，更新到飞书上啦[Idea全家桶激活教程](https://riid7yr8pux.feishu.cn/docx/TxGhdiMg1oDVbexEuUKcQG7nnYe?from=from_copylink)

**Comment by huaxiaobin** [comment]
@LiJunYi2 大佬，mac的dmg文件失效了，还有嘛，阿里网盘的打不开

**Comment by LiJunYi2** [comment]
> @LiJunYi2 大佬，mac的dmg文件失效了，还有嘛，阿里网盘的打不开

链接：https://pan.quark.cn/s/f48fe6b5c43a
提取码：1qhu

**Comment by huaxiaobin** [comment]
> > @LiJunYi2 大佬，mac的dmg文件失效了，还有嘛，阿里网盘的打不开
> 
> 链接：https://pan.quark.cn/s/f48fe6b5c43a 提取码：1qhu

可以了，谢谢大佬

**Comment by aoveig** [comment]
> > @LiJunYi2大佬，mac的dmg文件失效了，还有嘛，阿里网盘的打不开
> 
> 链接：https://pan.quark.cn/s/f48fe6b5c43a 提取码：1qhu

您好，大佬，我运行这个软件的时候报错是怎么回事呀

**Comment by LiJunYi2** [comment]
> > > @LiJunYi2大佬，mac的dmg文件失效了，还有嘛，阿里网盘的打不开
> 
> > 
> 
> > 链接：https://pan.quark.cn/s/f48fe6b5c43a 提取码：1qhu
> 
> 
> 
> 您好，大佬，我运行这个软件的时候报错是怎么回事呀

报了什么错？最好贴个图哈。

**Comment by aoveig** [comment]
> > > > @LiJunYi2大佬，mac的dmg文件失效了，还有嘛，阿里网盘的打不开
> > 
> > 
> > > 
> > 
> > 
> > > 链接：https://pan.quark.cn/s/f48fe6b5c43a提取码：1qhu
> > 
> > 
> > 您好，大佬，我运行这个软件的时候报错是怎么回事呀
> 
> 报什么错误？最好贴个图哈。
<img width="241" alt="截屏2023-11-12 22 27 53" src="https://github.com/LiJunYi2/navicat-keygen-16V/assets/124792322/236d752b-1945-464a-8c73-b9de2d049a2d">

**Comment by LiJunYi2** [comment]
> > > > > @LiJunYi2大佬，mac的dmg文件失效了，还有嘛，阿里网盘的打不开
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 链接：https://pan.quark.cn/s/f48fe6b5c43a提取码：1qhu
> 
> > > 
> 
> > > 
> 
> > > 您好，大佬，我运行这个软件的时候报错是怎么回事呀
> 
> > 
> 
> > 报什么错误？最好贴个图哈。
> 
> <img width="241" alt="截屏2023-11-12 22 27 53" src="https://github.com/LiJunYi2/navicat-keygen-16V/assets/124792322/236d752b-1945-464a-8c73-b9de2d049a2d">
> 
> 

😂😂报错信息呢？不是3s后显示报错信息嘛。先确认下，一个是需要从App Store下载，如果你本机原先已有navicat，需要先卸载干净再去App Store下载安装，安装完成后，先别打开，用破解程序激活后再打开。

**Comment by aoveig** [comment]
> > > > > > @LiJunYi2大佬，mac的dmg文件失效了，还有嘛，阿里网盘的打不开
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 链接：[https://pan.quark.cn/s/f48fe6b5c43a 提取码：1qhu](https://pan.quark.cn/s/f48fe6b5c43a%E6%8F%90%E5%8F%96%E7%A0%81%EF%BC%9A1qhu)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 您好，大佬，我运行这个软件的时候报错是怎么回事呀
> > 
> > 
> > > 
> > 
> > 
> > > 报什么错误？最好贴个图哈。
> > 
> > 
> > <img alt="截屏2023-11-12 22 27 53" width="241" src="https://user-images.githubusercontent.com/124792322/282305410-236d752b-1945-464a-8c73-b9de2d049a2d.png">
> 
> 😂😂报错信息呢？不是3秒后显示报错信息嘛。先确认下，一个是需要从App Store下载，如果你本机已经有navicat，需要先卸载干净再去App Store下载安装，安装完成后，先别打开，用破解程序激活后再打开。

没有报错信息😂😂，三秒后给我弹了个输入debug密码的框，我在重新来一遍，感谢大佬

**Comment by LiJunYi2** [comment]
> > > > > > > @LiJunYi2大佬，mac的dmg文件失效了，还有嘛，阿里网盘的打不开
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > 链接：[https://pan.quark.cn/s/f48fe6b5c43a 提取码：1qhu](https://pan.quark.cn/s/f48fe6b5c43a%E6%8F%90%E5%8F%96%E7%A0%81%EF%BC%9A1qhu)
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 您好，大佬，我运行这个软件的时候报错是怎么回事呀
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 报什么错误？最好贴个图哈。
> 
> > > 
> 
> > > 
> 
> > > <img alt="截屏2023-11-12 22 27 53" width="241" src="https://user-images.githubusercontent.com/124792322/282305410-236d752b-1945-464a-8c73-b9de2d049a2d.png">
> 
> > 
> 
> > 😂😂报错信息呢？不是3秒后显示报错信息嘛。先确认下，一个是需要从App Store下载，如果你本机已经有navicat，需要先卸载干净再去App Store下载安装，安装完成后，先别打开，用破解程序激活后再打开。
> 
> 
> 
> 
> 
>   没有没有出现报错信息😂😂，三秒后给我弹了个输入debug密码的框，我在重新来一遍，感谢大佬

好吧😂我以为会有错误信息，你先重试一次，不行的话，按弹窗提示发个邮件给macapp看看。

**Comment by acanyo** [comment]
> > > > > > > > @LiJunYi2大佬，mac的dmg文件失效了，还有嘛，阿里网盘的打不开
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > 链接：[https://pan.quark.cn/s/f48fe6b5c43a 提取码：1qhu](https://pan.quark.cn/s/f48fe6b5c43a%E6%8F%90%E5%8F%96%E7%A0%81%EF%BC%9A1qhu)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 您好，大佬，我运行这个软件的时候报错是怎么回事呀
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 报什么错误？最好贴个图哈。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > <img alt="截屏2023-11-12 22 27 53" width="241" src="https://user-images.githubusercontent.com/124792322/282305410-236d752b-1945-464a-8c73-b9de2d049a2d.png">
> > 
> > 
> > > 
> > 
> > 
> > > 😂😂报错信息呢？不是3秒后显示报错信息嘛。先确认下，一个是需要从App Store下载，如果你本机已经有navicat，需要先卸载干净再去App Store下载安装，安装完成后，先别打开，用破解程序激活后再打开。
> > 
> > 
> > 没有出现报错信息😂😂，三秒后给我弹了个输入debug密码的框，我在重新来一遍，谢谢大佬
> 
> 好吧😂我以为会有错误信息，你先重试一次，不行的话，按弹窗提示发个邮件给macapp看看。

我现在这个问题，请问你解决了吗

**Comment by wangpanying** [comment]
我现在也是出现内部错误然后三秒后给我弹了个输入debug密码的框 试了多次都是这样

**Comment by LiJunYi2** [comment]
> 我现在也是出现内部错误然后三秒后给我弹了个输入debug密码的框 试了多次都是这样

可能有些是无法使用，我本机目前还是正常。你的设备和系统是多少呀？

**Comment by wangpanying** [comment]
和你的一样 [
![Uploading 1702516534704.jpg…]()
](url)

**Comment by wangpanying** [comment]
![1702516534704](https://github.com/LiJunYi2/navicat-keygen-16V/assets/38452748/95238d55-b843-459e-9256-1c408918a41d)

**Comment by LiJunYi2** [comment]
> ![1702516534704](https://private-user-images.githubusercontent.com/38452748/290370361-95238d55-b843-459e-9256-1c408918a41d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MTc2NDEsIm5iZiI6MTcwMjUxNzM0MSwicGF0aCI6Ii8zODQ1Mjc0OC8yOTAzNzAzNjEtOTUyMzhkNTUtYjg0My00NTllLTkyNTYtMWM0MDg5MThhNDFkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAxMjkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlYWM1ODBmMTYxYzkwOTVlY2ZkMWRkY2EzYjJjOTQ3ZWJhYjIxYzgyYzY0NDllY2FkY2I5MGU5YTNmNDU1NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zUHk4-fxEV2oP39WxrEoLIdKg2ExkbJYrrswafPe_s4)

这就有点迷惑了，你试试xclient 上的：
https://www.123pan.com/s/YheEjv-6P1Xv.html
提取码:2vO3

**Comment by acanyo** [comment]
我已经好了




ㅤ
***@***.***







                       
原始邮件
                       
                     

发件人："LiXiaoJun"< ***@***.*** &gt;;

发件时间：2023/12/14 9:30

收件人："LiJunYi2/navicat-keygen-16V"< ***@***.*** &gt;;

抄送人："Handsome"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [LiJunYi2/navicat-keygen-16V] MAC AppStore 版本16.1.0 及后续版本通杀 (Issue #17)




  

  
这就有点迷惑了，你试试xclient 上的：
 https://www.123pan.com/s/YheEjv-6P1Xv.html
 提取码:2vO3

**Comment by LiJunYi2** [comment]
> > 我已经好了 ㅤ _**@**_.*** 原始邮件 发件人："LiXiaoJun"< _**@**_.*** >; 发件时间：2023/12/14 9:30 收件人："LiJunYi2/navicat-keygen-16V"< _**@**_.*** >; 抄送人："Handsome"< _**@**_.*** >;"Comment"< _**@**_.*** >; 主题：Re: [LiJunYi2/navicat-keygen-16V] MAC AppStore 版本16.1.0 及后续版本通杀 (Issue #17) 这就有点迷惑了，你试试xclient 上的： https://www.123pan.com/s/YheEjv-6P1Xv.html 提取码:2vO3 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 你怎么解决的

😂😂误删了，我以为是邮箱自动回复的。 @acanyo

**Comment by liuyiwuqing** [comment]
呜呜呜，mac端，从16.3.3更新到16.3.4，歇菜了，各位小伙伴勿升级

**Comment by wangpanying** [comment]
哈 那应该就是最新版本的问题 有之前版本的安装包吗

**Comment by liuyiwuqing** [comment]
> 哈 那应该就是最新版本的问题 有之前版本的安装包吗

没有，是通过App Store安装的

**Comment by LiJunYi2** [comment]
> 16.3.2 版本

用 xclient 的16.3.2 版本吧

**Comment by LiJunYi2** [comment]
> 哈 那应该就是最新版本的问题 有之前版本的安装包吗

先用 xclient 的 16.3.2 版本吧，等新的出了再说😂

**Comment by acanyo** [comment]
> > 我已经好了 ㅤ _**@**_.*** 原始邮件 发件人："LiXiaoJun"< _**@**_.*** >; 发件时间：2023/12/14 9:30 收件人："LiJunYi2/navicat-keygen-16V"< _**@**_.*** >; 抄送人："Handsome"< _**@**_.*** >;"Comment"< _**@**_.*** >; 主题：Re: [LiJunYi2/navicat-keygen-16V] MAC AppStore 版本16.1.0 及后续版本通杀 (Issue #17) 这就有点迷惑了，你试试xclient 上的： https://www.123pan.com/s/YheEjv-6P1Xv.html 提取码:2vO3 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 你怎么解决的

我用的其他版本 不是这个破解的

**Comment by wangpanying** [comment]
> > 哈 那应该就是最新版本的问题 有之前版本的安装包吗
> 
> 先用 xclient 的 16.3.2 版本吧，等新的出了再说😂

![1702516534704](https://github.com/LiJunYi2/navicat-keygen-16V/assets/38452748/97a3e348-b38c-4e4c-bd0d-b4c85c21df67)
什么情况

**Comment by LiJunYi2** [comment]
> > > 哈 那应该就是最新版本的问题 有之前版本的安装包吗
> > 
> > 
> > 先用 xclient 的 16.3.2 版本吧，等新的出了再说😂
> > ![1702519961590](https://private-user-images.githubusercontent.com/38452748/290378399-ae203473-60a8-43c8-9124-c3351c249fe5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjA0MDcsIm5iZiI6MTcwMjUyMDEwNywicGF0aCI6Ii8zODQ1Mjc0OC8yOTAzNzgzOTktYWUyMDM0NzMtNjBhOC00M2M4LTkxMjQtYzMzNTFjMjQ5ZmU1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAyMTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYjBjOWQwZDJjY2EwNzA5NGQ2NWFlYTNiYWRkZjE3MmZiZjVmYTM4MmMwYTM5NTFlYWEwNjJjNjFhMmY5MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R6XqRG8Smcd6m8t8uWfn8P3CkAgNCziR8aEymIcJW88)
> 
> 什么情况

1、打开终端；
2、输入以下命令，回车；
`sudo xattr -d com.apple.quarantine /Applications/xxxx.app`

注意：`/Applications/xxxx.app` 换成你的App路径（推荐直接将.app文件拖入终端中自动生成路径，以防空格等转义字符手动复制或输入出现错误）

3、重启App即可。

**Comment by wangpanying** [comment]
呜呜 成功了 感谢大佬

**Comment by VznMaGh** [comment]
![image](https://github.com/LiJunYi2/navicat-keygen-16V/assets/20884933/4f1d9bac-ee57-401e-9cdc-e4ae90ba9dbb)
Debug密码去哪里弄

**Comment by LiJunYi2** [comment]
> xclient 16.3.2版本

出现这个说明无效了，看评论顶部 **xclient 16.3.2版本**。

**Comment by LiJunYi2** [comment]
> ![image](https://private-user-images.githubusercontent.com/20884933/290438514-4f1d9bac-ee57-401e-9cdc-e4ae90ba9dbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MzkwMzIsIm5iZiI6MTcwMjUzODczMiwicGF0aCI6Ii8yMDg4NDkzMy8yOTA0Mzg1MTQtNGYxZDliYWMtZWU1Ny00MDFlLTljZGMtZTRhZTkwYmE5ZGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA3MjUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NjhiMjVlOWM4ZGQ1ODQ3NzAzMTIzMDhiMWU3NmJiODY3NDFiOGRlNjFiMDJlNjIwMjQ3ZTFkOWJjMzIxNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NMqvHeIzsjrqcgTdXUfOW8HwpiWrTsvftyC5xDqHzp8) Debug密码去哪里弄

出现这个说明无效了，看评论顶部 xclient 16.3.2版本。

**Comment by Mockingbird-io** [comment]
> > > > 哈 那应该就是最新版本的问题 有之前版本的安装包吗
> > > 
> > > 
> > > 先用 xclient 的 16.3.2 版本吧，等新的出了再说😂
> > > ![1702519961590](https://private-user-images.githubusercontent.com/38452748/290378399-ae203473-60a8-43c8-9124-c3351c249fe5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjA0MDcsIm5iZiI6MTcwMjUyMDEwNywicGF0aCI6Ii8zODQ1Mjc0OC8yOTAzNzgzOTktYWUyMDM0NzMtNjBhOC00M2M4LTkxMjQtYzMzNTFjMjQ5ZmU1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAyMTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYjBjOWQwZDJjY2EwNzA5NGQ2NWFlYTNiYWRkZjE3MmZiZjVmYTM4MmMwYTM5NTFlYWEwNjJjNjFhMmY5MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R6XqRG8Smcd6m8t8uWfn8P3CkAgNCziR8aEymIcJW88)
> > 
> > 
> > 什么情况
> 
> 1、打开终端； 2、输入以下命令，回车； `sudo xattr -d com.apple.quarantine /Applications/xxxx.app`
> 
> 注意：`/Applications/xxxx.app` 换成你的App路径（推荐直接将.app文件拖入终端中自动生成路径，以防空格等转义字符手动复制或输入出现错误）
> 
> 3、重启App即可。

<img width="948" alt="image" src="https://github.com/LiJunYi2/navicat-keygen-16V/assets/18682588/84e26bd0-fd57-4ff6-851e-4d760c9caa96">
老哥我怎么执行命令报错了

**Comment by LiJunYi2** [comment]
> sudo xattr -d com.apple.quarantine

使用默认终端运行试试？

**Comment by taozuhong** [comment]
公开破解商业软件并传播破解工具，不怕被公安请去喝茶？

**Comment by taozuhong** [comment]
![Workspace](https://github.com/LiJunYi2/navicat-keygen-16V/assets/13451009/a57b7fe8-aea8-4f1c-926e-374e6b03c27b)
![Kangaroo-newlook2](https://github.com/LiJunYi2/navicat-keygen-16V/assets/13451009/1e932afe-e78a-4086-ac73-dfaf6eadb921)

**Comment by LUOZZHENG** [comment]
> > > > > 哈 那应该就是最新版本的问题 有之前版本的安装包吗
> > > > 
> > > > 
> > > > 先用 xclient 的 16.3.2 版本吧，等新的出了再说😂
> > > > ![1702519961590](https://private-user-images.githubusercontent.com/38452748/290378399-ae203473-60a8-43c8-9124-c3351c249fe5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjA0MDcsIm5iZiI6MTcwMjUyMDEwNywicGF0aCI6Ii8zODQ1Mjc0OC8yOTAzNzgzOTktYWUyMDM0NzMtNjBhOC00M2M4LTkxMjQtYzMzNTFjMjQ5ZmU1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAyMTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYjBjOWQwZDJjY2EwNzA5NGQ2NWFlYTNiYWRkZjE3MmZiZjVmYTM4MmMwYTM5NTFlYWEwNjJjNjFhMmY5MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R6XqRG8Smcd6m8t8uWfn8P3CkAgNCziR8aEymIcJW88)
> > > 
> > > 
> > > 什么情况
> > 
> > 
> > 1、打开终端； 2、输入以下命令，回车； `sudo xattr -d com.apple.quarantine /Applications/xxxx.app`
> > 注意：`/Applications/xxxx.app` 换成你的App路径（推荐直接将.app文件拖入终端中自动生成路径，以防空格等转义字符手动复制或输入出现错误）
> > 3、重启App即可。
> 
> <img alt="image" width="948" src="https://private-user-images.githubusercontent.com/18682588/290762007-84e26bd0-fd57-4ff6-851e-4d760c9caa96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MDc5MTEsIm5iZiI6MTcwNjQwNzYxMSwicGF0aCI6Ii8xODY4MjU4OC8yOTA3NjIwMDctODRlMjZiZDAtZmQ1Ny00ZmY2LTg1MWUtNGQ3NjBjOWNhYTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAyMDY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMjU2MDVkNGQzODRlMjU4ZWFhOTNlYWI2YmQ1NDA2NTYxNWE5YWI4ZmEwMDYzMzM5NzM2NTFkZjJjYzI2MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R42PvRVeYt4jrCzj89uC2yReOv2rD7buMycPjR6352c"> 老哥我怎么执行命令报错了

我也出现这个问题，老哥解决了吗？

**Comment by semyon18** [comment]
xclient 16.3.2版本 分享的文件已经过期了，大佬能再发一次吗

**Comment by LiJunYi2** [comment]
> xclient 16.3.2版本 分享的文件已经过期了，大佬能再发一次吗

直接去 release 下载16.3.7版本的。
