### ISSUE TITLE
遇到一个问题求助各位，我使用Navicat 16 for PostgreSQL升级到16.3.2之后提示如下，激活已经过期 过期日期2023/04/19

### ISSUE THREAD

**Issue by yanxuzi** [LiJunYi2/navicat-keygen-16V#18]
激活已经过期 过期日期2023/04/19
该如何解决呢

**Comment by yanxuzi** [comment]
使用的UninstallTool卸载重装之后，一样的提示

**Comment by LiJunYi2** [comment]
> 使用的UninstallTool卸载重装之后，一样的提示

有没有可能，这是 `Navicat`的破解脚本，不是`Navicat 16 for PostgreSQL`的破解脚本

**Comment by LiJunYi2** [comment]
> 使用的UninstallTool卸载重装之后，一样的提示

先降版本吧，连 `Navicat` 16.3.2目前都还没人反馈能够正常升级

**Comment by yanxuzi** [comment]
> > 使用的UninstallTool卸载重装之后，一样的提示
> 
> 先降版本吧，连 `Navicat` 16.3.2目前都还没人反馈能够正常升级

好的。感谢回复。新电脑安装，可以正常使用。

**Comment by yanxuzi** [comment]
找到了一个解决办法。当你是从老版本升级到16.3.2的时候，不论你使用的是Navicat 16 for PostgreSQL，Navicat 16 for Oracle或者其他端。提示的时间距离现在时间比较远，需要激活，无法正常使用。这个时候可以去注册表删除HKEY_CURRENT_USER\Software\PremiumSoft 下对应的键即可。【请注意：此删除后客户端的连接记录便不存在了，你可以断掉主机的网络，设置主机的时间为提示你的截止时间之前，此时你打开工具是可以正常使用的，把连接导出即可】

**Comment by yanxuzi** [comment]
wanjie .

**Comment by yanxuzi** [comment]
over

**Comment by yanxuzi** [comment]
close.
