### ISSUE TITLE
新电脑，没有安装过其他版本，还是出现下面的错误

### ISSUE THREAD

**Issue by Barry04** [LiJunYi2/navicat-keygen-16V#2]
![image](https://user-images.githubusercontent.com/61132615/183556314-595f816e-8f77-4ce7-8d9c-77a9c71075f6.png)

**Comment by LiJunYi2** [comment]
navicat是哪个版本？是点击Patch报的错误吗

**Comment by LiJunYi2** [comment]
> ![image](https://user-images.githubusercontent.com/61132615/183556314-595f816e-8f77-4ce7-8d9c-77a9c71075f6.png)

navicat是哪个版本？是点击`Patch`报的错吗

**Comment by Barry04** [comment]
16的，官网下载的最新的

**Comment by LiJunYi2** [comment]
> 16的，官网下载的最新的

我刚把我本机的navicat最新版卸载了重新装了一下，点击`Patch`后正常，你可以用 `geek`卸载工具先卸载掉现在的，然后重新安装一下navicat，路径不要有中文、空格。

**Comment by Barry04** [comment]
好的，谢谢你，已经成功解决了，最好说明一下安装路径不要有中文、空格。我前面的就是因为有，所以没有成功。现在成功了

**Comment by LiJunYi2** [comment]
> 好的，谢谢你，已经成功解决了，最好说明一下安装路径不要有中文、空格。我前面的就是因为有，所以没有成功。现在成功了

好滴，晚点重新编辑下教程😁
