### ISSUE TITLE
激活成功后，无法升级版本了

### ISSUE THREAD

**Issue by Gao-sy** [LiJunYi2/navicat-keygen-16V#29]
今天下载了下16.1的版本，然后按步骤激活后，显示激活成功
![Snipaste_2024-02-16_07-48-14](https://github.com/LiJunYi2/navicat-keygen-16V/assets/76046239/52dd566f-fc01-4883-9acb-38e0cd69d844)
然后检查更新，想要升级为16.3.5，但是一点下载后就显示无法连接到服务器，电脑网络是没有问题的
![Snipaste_2024-02-16_07-48-30](https://github.com/LiJunYi2/navicat-keygen-16V/assets/76046239/0c24e6ad-06ad-443c-86b0-01c7250494ee)
![Snipaste_2024-02-16_07-48-40](https://github.com/LiJunYi2/navicat-keygen-16V/assets/76046239/fe9f7cc9-7d05-4b5a-8e86-dd9e64e8c92b)

**Comment by LiJunYi2** [comment]
直接官方下载 exe 程序覆盖安装就行，升级不是问题。

**Comment by Gao-sy** [comment]
> 直接官方下载 exe 程序覆盖安装就行，升级不是问题。

试过了，显示激活失败了就

**Comment by LiJunYi2** [comment]
> > 直接官方下载 exe 程序覆盖安装就行，升级不是问题。
> 
> 
> 
> 试过了，显示激活失败了就

2.x的激活方式变了，看看release, 注册机在2.x不适用了

**Comment by Gao-sy** [comment]
> > > 直接官方下载 exe 程序覆盖安装就行，升级不是问题。
> > 
> > 
> > 试过了，显示激活失败了就
> 
> 2.x的激活方式变了，看看release, 注册机在2.x不适用了

ok

**Comment by LiJunYi2** [comment]
手滑删错了，2.x以上版本看看release 有说明，注册机在最新版已经不适用了
