### ISSUE TITLE
这个注册机需要联网吗？还是Navcat本身需要联网激活？

### ISSUE THREAD

**Issue by Barry04** [LiJunYi2/navicat-keygen-16V#3]
这个注册机需要联网吗？还是Navcat本身需要联网激活？我在一台无互联网的环境破解，只会显示激活不成功！

**Comment by LiJunYi2** [comment]
> 这个注册机需要联网吗？还是Navcat本身需要联网激活？我在一台无互联网的环境破解，只会显示激活不成功！

可以在无网络下使用，我刚试了下断网可以正常安装以及激活。按照 [激活教程](https://lijunyi.xyz/blogs/app/2022/NavicatPremium16.html) 来

**Comment by LiJunYi2** [comment]
![1](https://user-images.githubusercontent.com/40384503/187619519-e1f275ff-a498-4551-9d82-c42cb59c6066.png)

**Comment by Barry04** [comment]
但是我没成功，我只在有网络情况下成功了，安装教程，然后我在 C:\Windows\System32\drivers\etc 路径下的 hosts 文件末尾添加如下内容达到屏蔽Navicat激活服务器  
127.0.0.1       activate.navicat.com
![image](https://user-images.githubusercontent.com/61132615/187620593-af0abbe0-92cf-409d-943a-44a2593fd59e.png)

这是我在网上找的一个方法，我只能在hosts文件加了上面的内容就成功了。
也可能是我之前的操作有问题，但也不太可能，我都试过几遍了，然后加了上面的操作就一次性成功了。

**Comment by Barry04** [comment]
应该是我之前的操作问题

**Comment by LiJunYi2** [comment]
> 但是我没成功，我只在有网络情况下成功了，安装教程，然后我在 C:\Windows\System32\drivers\etc 路径下的 hosts 文件末尾添加如下内容达到屏蔽Navicat激活服务器 127.0.0.1 activate.navicat.com ![image](https://user-images.githubusercontent.com/61132615/187620593-af0abbe0-92cf-409d-943a-44a2593fd59e.png)
> 
> 这是我在网上找的一个方法，我只能在hosts文件加了上面的内容就成功了。 也可能是我之前的操作有问题，但也不太可能，我都试过几遍了，然后加了上面的操作就一次性成功了。

那可能是第一步没有勾选`HOSTS`，教程里面其实也有说的，最好是确保添加了这个。现在能激活就好。
![image](https://user-images.githubusercontent.com/40384503/187621663-14ed11db-2a22-4ebc-beb1-1f13f929c7fa.png)
