### ISSUE TITLE
如何查看是否激活

### ISSUE THREAD

**Issue by super117893344p** [LiJunYi2/navicat-keygen-16V#30]
我是最新版本 16.3.8 最后搞完没弹出注册激活码界面 , 直接进去了. 但是点开注册按钮
![image](https://github.com/LiJunYi2/navicat-keygen-16V/assets/129602465/3d1ee86a-6061-43a4-bec4-d3f4358b8ae1)
![image](https://github.com/LiJunYi2/navicat-keygen-16V/assets/129602465/027469f4-b08c-4f65-a3fd-4aaa49c06dd5)
提示需要许可证 ,请问这到底是试用还是已经激活了呢?

**Comment by LiJunYi2** [comment]
可以在这个[issues](https://github.com/LiJunYi2/navicat-keygen-16V/issues/11) 里问问已经测试成功的小伙伴。
