### ISSUE TITLE
win 16.2 没有激活

### ISSUE THREAD

**Issue by a224327780** [LiJunYi2/navicat-keygen-16V#31]
![image](https://github.com/LiJunYi2/navicat-keygen-16V/assets/78008038/adc41c45-1531-4bbf-b03e-a5bdd4bacf01)
![image](https://github.com/LiJunYi2/navicat-keygen-16V/assets/78008038/a8194c90-4f19-45de-8c8e-987a728c0b9a)

这个流程操作了N次还是提示试用
![image](https://github.com/LiJunYi2/navicat-keygen-16V/assets/78008038/61c10553-6705-4097-964d-25e0b8e6ce1e)

**Comment by LiJunYi2** [comment]
1、下最新版本试试。
2、到这个[issues](https://github.com/LiJunYi2/navicat-keygen-16V/issues/11) 提问一下，`16.2.11`版本在评论区有提到过，可以激活。

**Comment by a224327780** [comment]
![image](https://github.com/LiJunYi2/navicat-keygen-16V/assets/78008038/45c2a29b-eda3-4d7b-953c-023ef65d7dcb)
16.3.8 也没激活

不知道是不是又其他版本，一打开就有配置
![image](https://github.com/LiJunYi2/navicat-keygen-16V/assets/78008038/a2c774d7-6272-4a86-b401-8256cb04e240)

**Comment by LiJunYi2** [comment]
> ![image](https://private-user-images.githubusercontent.com/78008038/311961086-45c2a29b-eda3-4d7b-953c-023ef65d7dcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjQxNTYsIm5iZiI6MTcxMDIyMzg1NiwicGF0aCI6Ii83ODAwODAzOC8zMTE5NjEwODYtNDVjMmEyOWItZWRhMy00ZDdiLTk1M2MtMDIzZWY2NWQ3ZGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA2MTA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZTgwNzRmOWFlODhmM2U1YjBlYjI1YjdiYWE5ZTczYzVjMTcyNjAwNDgwMDIwYzA2MGM4MTNhNTMyZTQ2NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PEYYOQwWUCQ_Zy5RK9rWgo-F-JunThneipBDIbYCb2Q) 16.3.8 也没激活
> 
> 不知道是不是又其他版本，一打开就有配置 ![image](https://private-user-images.githubusercontent.com/78008038/311961194-a2c774d7-6272-4a86-b401-8256cb04e240.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjQxNTYsIm5iZiI6MTcxMDIyMzg1NiwicGF0aCI6Ii83ODAwODAzOC8zMTE5NjExOTQtYTJjNzc0ZDctNjI3Mi00YTg2LWI0MDEtODI1NmNiMDRlMjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA2MTA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNGUyOTU5MjlhNmVhMDBiMDRjOTU4YTg0NWFjMjgzMzE2NjBmYjVhNmFmNjMyZDEyNThmYzYzYzE4YjYzOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B50lrrY9-LWGXETI__pf6dWlUa7pEQWhhClV55WEpRc)

<img width="780" alt="image" src="https://github.com/LiJunYi2/navicat-keygen-16V/assets/40384503/75583eee-61c6-4a48-8048-60147b71cd4c">
这个才是正常的，实在不行，你就换重置脚本，配合 win 的定时任务。
