### ISSUE TITLE
无法连接orcale

### ISSUE THREAD

**Issue by qq1005894049** [LiJunYi2/navicat-keygen-16V#35]
没有orcale oci环境

**Comment by LiJunYi2** [comment]
使用问题请自行解决，下方链接供参考：
[oracle instant-client](https://www.oracle.com/database/technologies/instant-client/winx64-64-downloads.html)
[navicat help](https://www.navicat.com.cn/support/help/%E5%BD%93%E6%88%91%E5%9C%A8-navicat-%E5%B0%9D%E8%AF%95%E5%88%9B%E5%BB%BA%E8%BF%9E%E6%8E%A5%E5%88%B0-oracle-%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%97%B6%EF%BC%8C%E6%88%91%E5%BE%97%E5%88%B0%E4%B8%80%E4%B8%AA%E9%94%99%E8%AF%AF%E4%BF%A1%E6%81%AF%E8%AF%B4-instant-client-%E6%98%AF%E5%BF%85%E9%9C%80%E7%9A%84%E3%80%82%E9%82%A3%E6%98%AF%E4%BB%80%E4%B9%88%EF%BC%8C%E5%BA%94%E8%AF%A5%E6%80%8E%E4%B9%88%E5%8A%9E%EF%BC%9F)
