### ISSUE TITLE
今天帮别人安装时出现的问题。。。

### ISSUE THREAD

**Issue by Barry04** [LiJunYi2/navicat-keygen-16V#4]
![lQLPJxapqiLJsITNA4nNArKwvdziQu6-J6oDFwt2qcCJAA_690_905](https://user-images.githubusercontent.com/61132615/188773198-6cccba4c-4e96-45f8-9f22-a0c54ddbef0a.png)
无空格，无中文，HOSTS有东西

**Comment by Barry04** [comment]
![lQLPJxapqsypODPNAuHNApGwmek32YvZYqIDFwyMaEBjAA_657_737](https://user-images.githubusercontent.com/61132615/188773468-652eeb0e-d7f2-4b48-b003-d15187436326.png)
前面的问题没出现了，又出现该图的问题

**Comment by LiJunYi2** [comment]
> ![lQLPJxapqsypODPNAuHNApGwmek32YvZYqIDFwyMaEBjAA_657_737](https://user-images.githubusercontent.com/61132615/188773468-652eeb0e-d7f2-4b48-b003-d15187436326.png) 前面的问题没出现了，又出现该图的问题

第一个是因为你勾选了RSA KEY，这个不能勾选，然后第二个，可能因为你第一次勾选了RAS KEY导致的，你试一下删除注册机同目录下的`Navicat_2048bit_rsa_private_key.pem` 这个文件

**Comment by Barry04** [comment]
我是先试了没有勾选RSA KEY的，不行，然后才勾选他的

**Comment by Barry04** [comment]
大佬有无联系方式加一下，方便实时反馈

**Comment by LiJunYi2** [comment]
> 我是先试了没有勾选RSA KEY的，不行，然后才勾选他的

那只能先卸载再重新安装了😂重装大法好

**Comment by LiJunYi2** [comment]
> 大佬有无联系方式加一下，方便实时反馈

Q：2510807765

**Comment by Barry04** [comment]
我刚刚帮他重新卸载，安装又可以了，谢谢大佬

**Comment by LiJunYi2** [comment]
> 我刚刚帮他重新卸载，安装又可以了，谢谢大佬

没事😁😁
