### ISSUE TITLE
16.1.3卡死

### ISSUE THREAD

**Issue by Lvbuqing** [LiJunYi2/navicat-keygen-16V#5]
![image](https://user-images.githubusercontent.com/32841009/195772779-53a9dd1a-0d44-4047-936d-d9abbb631352.png)
![image](https://user-images.githubusercontent.com/32841009/195772850-2d1f67fb-ec44-4e2b-a168-2b874666d1df.png)

**Comment by LiJunYi2** [comment]
> ![image](https://user-images.githubusercontent.com/32841009/195772779-53a9dd1a-0d44-4047-936d-d9abbb631352.png) ![image](https://user-images.githubusercontent.com/32841009/195772850-2d1f67fb-ec44-4e2b-a168-2b874666d1df.png)

亲测最新版16.1.3正常激活
![code](https://user-images.githubusercontent.com/40384503/195774214-aeaae159-6e17-4415-b0cd-8ff907a09b10.png)

我猜，你应该是navicat16的安装目录没有选择正确导致卡死

**Comment by Lvbuqing** [comment]
目录是对的
直接定位到C:\Program Files\PremiumSoft\Navicat Premium 16
![image](https://user-images.githubusercontent.com/32841009/195774876-9ef4eab8-d9c4-4de8-934b-82e30f6745bc.png)
![image](https://user-images.githubusercontent.com/32841009/195774940-d3b9c669-f9b0-4ca3-a485-1466d1a9c13f.png)

**Comment by LiJunYi2** [comment]
> 目录是对的 直接定位到C:\Program Files\PremiumSoft\Navicat Premium 16 ![image](https://user-images.githubusercontent.com/32841009/195774876-9ef4eab8-d9c4-4de8-934b-82e30f6745bc.png) ![image](https://user-images.githubusercontent.com/32841009/195774940-d3b9c669-f9b0-4ca3-a485-1466d1a9c13f.png)

你navicat是装在C盘？你之前有装过其他版本吗？然后卸载是完全卸载掉了吗

**Comment by Lvbuqing** [comment]
新装的，我电脑就一个盘

**Comment by LiJunYi2** [comment]
> 新装的，我电脑就一个盘

方便远程看下吗？

**Comment by Lvbuqing** [comment]
我刚使用了另一款激活软件激活了，需要卸载吗

**Comment by LiJunYi2** [comment]
> 我刚使用了另一款激活软件激活了，需要卸载吗

可以先卸掉，用 [geek](https://geekuninstaller.com/download?version=1.5.0.161)去卸载

**Comment by Lvbuqing** [comment]
![image](https://user-images.githubusercontent.com/32841009/195777612-56ca2d62-4e52-4564-b2f7-9b9d48cd6849.png)
用geek卸载了一遍，重装就可以了

**Comment by Lvbuqing** [comment]
感谢！

**Comment by LiJunYi2** [comment]
> 感谢！

👌🏼👌🏼好滴
