### ISSUE TITLE
Navicat Premium 16.2 现已正式发布 ,释放 Redis 全部潜能，keygen对其失效

### ISSUE THREAD

**Issue by jkxbest** [LiJunYi2/navicat-keygen-16V#6]
![image](https://github.com/LiJunYi2/navicat-keygen-16V/assets/38863227/32dcff65-bc88-456b-8d5a-1ef61e12f73f)

**Comment by LiJunYi2** [comment]
是的  刚测试了注册机对其无效，先使用`16.1.x`版本吧，有新的注册机会更新的

**Comment by MindaDai** [comment]
大佬啥时候能更新- -手贱点了更新 又没法回退 里面有些备份，没换出sql文件有点难受

**Comment by LiJunYi2** [comment]
> 大佬啥时候能更新- -手贱点了更新 又没法回退 里面有些备份，没换出sql文件有点难受

release里面有[16.1.15](https://github.com/LiJunYi2/navicat-keygen-16V/releases/tag/v16.1.15)的包，可以先安装这个版本，数据库链接文件先导出来。新版本破解出了会更新哒😂

**Comment by tinylit** [comment]
大佬，等你好消息。

**Comment by 1273082756** [comment]
大佬，等你好消息。

**Comment by BoneBee** [comment]
[Navicat16.2.3.zip](https://github.com/LiJunYi2/navicat-keygen-16V/files/11945536/Navicat16.2.3.zip)
按照教程

**Comment by LiJunYi2** [comment]
> [Navicat16.2.3.zip](https://github.com/LiJunYi2/navicat-keygen-16V/files/11945536/Navicat16.2.3.zip) 按照教程

NavicatForRedis也适用吗？我在`Releases`给你推一下可以不？

**Comment by BoneBee** [comment]
> > [Navicat16.2.3.zip](https://github.com/LiJunYi2/navicat-keygen-16V/files/11945536/Navicat16.2.3.zip)按照教程
> 
> NavicatForRedis 也适用吗？我在`Releases`给你推一下可以不？

没试过
16.2.3有redis
![image](https://github.com/LiJunYi2/navicat-keygen-16V/assets/48782834/2c266e9a-0298-4fc1-8c5e-ff7f7aaa96f3)

**Comment by BoneBee** [comment]
redis gui 使用官方的 RedisInsight-v2 免费

**Comment by LiJunYi2** [comment]
> > > [Navicat16.2.3.zip](https://github.com/LiJunYi2/navicat-keygen-16V/files/11945536/Navicat16.2.3.zip)按照教程
> > 
> > 
> > NavicatForRedis 也适用吗？我在`Releases`给你推一下可以不？
> 
> 没试过 16.2.3有redis ![image](https://user-images.githubusercontent.com/48782834/250789747-2c266e9a-0298-4fc1-8c5e-ff7f7aaa96f3.png)

好的，那我在`Releases`给你推下👍

**Comment by BoneBee** [comment]
ok

**Comment by yearspark** [comment]
牛逼啊

**Comment by tangqiu0205** [comment]
安全吗? 有点不敢用.

**Comment by LiJunYi2** [comment]
> 安全吗? 有点不敢用.

bat文件就是个删除navicat记录试用时间功能，dll文件可以用火绒扫描一下。毒应该是没的。

**Comment by 866666** [comment]
这个版本不能光用脚本无限试用了吗？

**Comment by LiJunYi2** [comment]
> 这个版本不能光用脚本无限试用了吗？
16.2版本，老的重置脚本无效了，试试最新的吧

**Comment by LiJunYi2** [comment]
> 这个版本不能光用脚本无限试用了吗？

16.2版本，老的重置脚本无效了，试试最新的吧

**Comment by tangqiu0205** [comment]
> 这个版本不能光用脚本无限试用了吗？



> > 安全吗? 有点不敢用.
> 
> bat文件就是个删除navicat记录试用时间功能，dll文件可以用火绒扫描一下。毒应该是没的。

 好的好的

**Comment by tangqiu0205** [comment]
> > > 安全吗? 有点不敢用.
> > 
> > 
> > bat文件就是个删除navicat记录试用时间功能，dll文件可以用火绒扫描一下。毒应该是没的。
> 
> > 安全吗? 有点不敢用.
> 
> 安全呀，我用的就是

嗯嗯

**Comment by xygzyf2008** [comment]
![image](https://github.com/LiJunYi2/navicat-keygen-16V/assets/4231482/a8700112-261c-4b8e-a816-f21d90d3dc72)
16.2.2已经不再提示未注册了，真香

**Comment by lyc8503** [comment]
新版 (16.2.3) 的重置试用脚本如下
```
echo Delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Update
reg delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Update /f
echo Delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Registration[version and language]
for /f %%i in ('"REG QUERY "HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium" /s | findstr /L Registration"') do (
    reg delete %%i /va /f
)

echo Delete Info and ShellFolder under HKEY_CURRENT_USER\Software\Classes\CLSID
for /f "tokens=*" %%a in ('reg query "HKEY_CURRENT_USER\Software\Classes\CLSID"') do (
  for /f "tokens=*" %%l in ('reg query "%%a" /f "Info" /s /e ^| findstr /i "Info"') do (
    echo Delete: %%a
    reg delete %%a /f
  )
  for /f "tokens=*" %%l in ('reg query "%%a" /f "ShellFolder" /s /e ^| findstr /i "ShellFolder"') do (
    echo Delete: %%a
    reg delete %%a /f
  )
)
```

**Comment by WPF-8236** [comment]
这个

> [Navicat16.2.3.zip](https://github.com/LiJunYi2/navicat-keygen-16V/files/11945536/Navicat16.2.3.zip) 按照教程

支持直接使用官方升级到16.2.5

**Comment by LiJunYi2** [comment]
> 这个
> 
> 
> 
> > [Navicat16.2.3.zip](https://github.com/LiJunYi2/navicat-keygen-16V/files/11945536/Navicat16.2.3.zip) 按照教程
> 
> 
> 
> 支持直接使用官方升级到16.2.5

棒滴很👍🏻

**Comment by ChengzhenDu** [comment]
感谢！

**Comment by Xiao-Ning-166** [comment]
> 新版 (16.2.3) 的重置试用脚本如下
> 
> ```
> echo Delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Update
> reg delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Update /f
> echo Delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Registration[version and language]
> for /f %%i in ('"REG QUERY "HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium" /s | findstr /L Registration"') do (
>     reg delete %%i /va /f
> )
> 
> echo Delete Info and ShellFolder under HKEY_CURRENT_USER\Software\Classes\CLSID
> for /f "tokens=*" %%a in ('reg query "HKEY_CURRENT_USER\Software\Classes\CLSID"') do (
>   for /f "tokens=*" %%l in ('reg query "%%a" /f "Info" /s /e ^| findstr /i "Info"') do (
>     echo Delete: %%a
>     reg delete %%a /f
>   )
>   for /f "tokens=*" %%l in ('reg query "%%a" /f "ShellFolder" /s /e ^| findstr /i "ShellFolder"') do (
>     echo Delete: %%a
>     reg delete %%a /f
>   )
> )
> ```

感谢大佬！

**Comment by menqy** [comment]
> [Navicat16.2.3.zip](https://github.com/LiJunYi2/navicat-keygen-16V/files/11945536/Navicat16.2.3.zip) 按照教程
感谢大佬

**Comment by ybwKame** [comment]
感谢大佬！

**Comment by LiJunYi2** [comment]
> 有16.2.3的安装包吗，现在官网只能下载到16.2.5了

16.2.5能激活！😎直接冲

**Comment by vacuole1989** [comment]
试了一下，上面的这个插件并不能激活，仅仅只是把试用的弹窗给屏蔽掉了，给人一种已经激活的感觉，实际上还是在试用，试用时间到了还是会提示过期不能用。

目前唯一能用的就是那个重置试用时间的脚本了。

**Comment by LiJunYi2** [comment]
> 试了一下，上面的这个插件并不能激活，仅仅只是把试用的弹窗给屏蔽掉了，给人一种已经激活的感觉，实际上还是在试用，试用时间到了还是会提示过期不能用。
> 
> 目前唯一能用的就是那个重置试用时间的脚本了。

这样的吗，我还以为是激活了的。再看看其他人的情况，如果都是这样我就去掉。

**Comment by vacuole1989** [comment]
> > 试了一下，上面的这个插件并不能激活，仅仅只是把试用的弹窗给屏蔽掉了，给人一种已经激活的感觉，实际上还是在试用，试用时间到了还是会提示过期不能用。
> > 目前唯一能用的就是那个重置试用时间的脚本了。
> 
> 这样的吗，我还以为是激活了的。再看看其他人的情况，如果都是这样我就去掉。

是的，我这边已经碰到过好几次了，而且如果有这个插件的情况下如果试用过期了会导致打开navicat没有任何反应，我把插件删掉以后才正常提示我navicat已过期。

**Comment by LiJunYi2** [comment]
> 

好的，感谢反馈，我去修正下

**Comment by WPF-8236** [comment]
> > > 试了一下，上面的这个插件并不能激活，仅仅只是把试用的弹窗给屏蔽掉了，给人一种已经激活的感觉，实际上还是在试用，试用时间到了还是会提示过期不能用。
> > > 目前唯一能用的就是那个重置试用时间的脚本了。
> > 
> > 
> > 这样的吗，我还以为是激活了的。再看看其他人的情况，如果都是这样我就去掉。
> 
> 是的，我这边已经碰到过好几次了，而且如果有这个插件的情况下如果试用过期了会导致打开navicat没有任何反应，我把插件删掉以后才正常提示我navicat已过期。

我用了快一个月没出现问题

**Comment by vacuole1989** [comment]
> > > > 试了一下，上面的这个插件并不能激活，仅仅只是把试用的弹窗给屏蔽掉了，给人一种已经激活的感觉，实际上还是在试用，试用时间到了还是会提示过期不能用。
> > > > 目前唯一能用的就是那个重置试用时间的脚本了。
> > > 
> > > 
> > > 这样的吗，我还以为是激活了的。再看看其他人的情况，如果都是这样我就去掉。
> > 
> > 
> > 是的，我这边已经碰到过好几次了，而且如果有这个插件的情况下如果试用过期了会导致打开navicat没有任何反应，我把插件删掉以后才正常提示我navicat已过期。
> 
> 我用了快一个月没出现问题

目前这个插件确实有问题，想要复现很简单，我刚刚全部卸载之后重新安装Navicat16.2.5，然后安装上了最新的插件，然后打开软件没问题。接下来我把系统时间改到15天之后的时间，再次打开Navicat16.2.5，出现欢迎界面之后就一闪而过，无法打开软件。这个时候删掉winmm.dll文件再双击打开，显示软件试用已过期。

**Comment by LiJunYi2** [comment]
> > > > > 试了一下，上面的这个插件并不能激活，仅仅只是把试用的弹窗给屏蔽掉了，给人一种已经激活的感觉，实际上还是在试用，试用时间到了还是会提示过期不能用。
> > > > > 目前唯一能用的就是那个重置试用时间的脚本了。
> > > > 
> > > > 
> > > > 这样的吗，我还以为是激活了的。再看看其他人的情况，如果都是这样我就去掉。
> > > 
> > > 
> > > 是的，我这边已经碰到过好几次了，而且如果有这个插件的情况下如果试用过期了会导致打开navicat没有任何反应，我把插件删掉以后才正常提示我navicat已过期。
> > 
> > 
> > 我用了快一个月没出现问题
> 
> 目前这个插件确实有问题，想要复现很简单，我刚刚全部卸载之后重新安装Navicat16.2.5，然后安装上了最新的插件，然后打开软件没问题。接下来我把系统时间改到15天之后的时间，再次打开Navicat16.2.5，出现欢迎界面之后就一闪而过，无法打开软件。这个时候删掉winmm.dll文件再双击打开，显示软件试用已过期。

我刚在Windows上测试了一下，navicat16.2.5安装之后，我把时间改成2024年还是可以打开，正常运行。
![Snipaste_2024-09-10_19-26-30](https://github.com/LiJunYi2/navicat-keygen-16V/assets/40384503/17239796-e630-4257-b74a-995481eddfaf)

**Comment by vacuole1989** [comment]
> > > > > > 试了一下，上面的这个插件并不能激活，仅仅只是把试用的弹窗给屏蔽掉了，给人一种已经激活的感觉，实际上还是在试用，试用时间到了还是会提示过期不能用。
> > > > > > 目前唯一能用的就是那个重置试用时间的脚本了。
> > > > > 
> > > > > 
> > > > > 这样的吗，我还以为是激活了的。再看看其他人的情况，如果都是这样我就去掉。
> > > > 
> > > > 
> > > > 是的，我这边已经碰到过好几次了，而且如果有这个插件的情况下如果试用过期了会导致打开navicat没有任何反应，我把插件删掉以后才正常提示我navicat已过期。
> > > 
> > > 
> > > 我用了快一个月没出现问题
> > 
> > 
> > 目前这个插件确实有问题，想要复现很简单，我刚刚全部卸载之后重新安装Navicat16.2.5，然后安装上了最新的插件，然后打开软件没问题。接下来我把系统时间改到15天之后的时间，再次打开Navicat16.2.5，出现欢迎界面之后就一闪而过，无法打开软件。这个时候删掉winmm.dll文件再双击打开，显示软件试用已过期。
> 
> 我刚在Windows上测试了一下，navicat16.2.5安装之后，我把时间改成2024年还是可以打开，正常运行。 ![Snipaste_2024-09-10_19-26-30](https://user-images.githubusercontent.com/40384503/259725836-17239796-e630-4257-b74a-995481eddfaf.png)

虚拟机安装了一个window10试了一下，确实没问题，估计是我本地电脑上没卸载干净的原因。

**Comment by magdsnail** [comment]
> > > 安全吗? 有点不敢用.
> > 
> > 
> > bat文件就是个删除navicat记录试用时间功能，dll文件可以用火绒扫描一下。毒应该是没的。
> 
> > 安全吗? 有点不敢用.
> 
> 安全呀，我用的就是

棒极了，完美，感谢，sqlyog13.2.0Trial能破解一下不

**Comment by WPF-8236** [comment]
已成功升级至16.2.7，应该16.2.x的都可以直接官方升级

**Comment by Miroxyz** [comment]
直接升级到16.2.7，然后执行 bat 重置，连卸载都不用。

**Comment by romypan** [comment]
为什么写sql语句表名，字段名不能智能提示呢，哪位兄弟遇到过？

**Comment by jkxbest** [comment]
你得切换到对应数据库

**Comment by taozuhong** [comment]
![image](https://github.com/LiJunYi2/navicat-keygen-16V/assets/13451009/0bc6469a-9ce1-4b93-997e-c85b556ff373)

**Comment by munan56** [comment]
> ![image](https://user-images.githubusercontent.com/13451009/264973324-0bc6469a-9ce1-4b93-997e-c85b556ff373.png)
> 
> ![image](https://user-images.githubusercontent.com/13451009/266996580-2a7ca600-a858-4aaa-9137-2556a1ada5c1.png)

what's this。
it looks very professional

**Comment by jkxbest** [comment]
https://www.datatable.online/en/

**Comment by AaronZSAM101** [comment]
> 直接升级到16.2.7，然后执行 bat 重置，连卸载都不用。

刚才更新了16.2.11 重新跑了一遍bat 依旧可用

**Comment by www3cc** [comment]
> 新版 (16.2.3) 的重置试用脚本如下
> 
> ```
> echo Delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Update
> reg delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Update /f
> echo Delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Registration[version and language]
> for /f %%i in ('"REG QUERY "HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium" /s | findstr /L Registration"') do (
>     reg delete %%i /va /f
> )
> 
> echo Delete Info and ShellFolder under HKEY_CURRENT_USER\Software\Classes\CLSID
> for /f "tokens=*" %%a in ('reg query "HKEY_CURRENT_USER\Software\Classes\CLSID"') do (
>   for /f "tokens=*" %%l in ('reg query "%%a" /f "Info" /s /e ^| findstr /i "Info"') do (
>     echo Delete: %%a
>     reg delete %%a /f
>   )
>   for /f "tokens=*" %%l in ('reg query "%%a" /f "ShellFolder" /s /e ^| findstr /i "ShellFolder"') do (
>     echo Delete: %%a
>     reg delete %%a /f
>   )
> )
> ```

真的是高手  繁體也適用
最近看有人亂下載dll檔或是exe  主機整個要附贈彼特幣
感謝大老...提供bat檔相對安全許多

**Comment by www3cc** [comment]
真的是高手 繁體也適用
最近看有人亂下載dll檔或是exe 主機整個要附贈彼特幣
感謝大老...提供bat檔相對安全許多

**Comment by www3cc** [comment]
@lyc8503 
真的是高手 繁體也適用
最近看有人亂下載dll檔或是exe 主機整個要附贈彼特幣
感謝大老...提供bat檔相對安全許多

**Comment by liyipeng726** [comment]
16.2.11版本执行了bat，成功了注册界面是啥样子的

**Comment by liyipeng726** [comment]
> > 直接升级到16.2.7，然后执行 bat 重置，连卸载都不用。
> 
> 刚才更新了16.2.11 重新跑了一遍bat 依旧可用

2.11版本成功了注册界面显示什么呀

**Comment by romypan** [comment]
为什么不能智能提示表名

**Comment by AaronZSAM101** [comment]
@liyipeng726 更新后执行完bat，在启动时界面如下：
![image](https://github.com/LiJunYi2/navicat-keygen-16V/assets/60245950/c4f69f97-4987-4165-b935-e77963684353)

以前使用Keygen时会显示个人信息、Keygen的一部分，执行完bat后就没有这些信息了。

**Comment by menqy** [comment]
![image](https://github.com/LiJunYi2/navicat-keygen-16V/assets/58165869/26de7968-3426-4b42-b074-12c20d082f35)
更新后每次第一次打开都提示这个，有好几个弹窗，必须都点确认之后，再次打开才可以

**Comment by yzy-1995** [comment]
> > 新版 (16.2.3) 的重置试用脚本如下
> > ```
> > echo Delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Update
> > reg delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Update /f
> > echo Delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Registration[version and language]
> > for /f %%i in ('"REG QUERY "HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium" /s | findstr /L Registration"') do (
> >     reg delete %%i /va /f
> > )
> > 
> > echo Delete Info and ShellFolder under HKEY_CURRENT_USER\Software\Classes\CLSID
> > for /f "tokens=*" %%a in ('reg query "HKEY_CURRENT_USER\Software\Classes\CLSID"') do (
> >   for /f "tokens=*" %%l in ('reg query "%%a" /f "Info" /s /e ^| findstr /i "Info"') do (
> >     echo Delete: %%a
> >     reg delete %%a /f
> >   )
> >   for /f "tokens=*" %%l in ('reg query "%%a" /f "ShellFolder" /s /e ^| findstr /i "ShellFolder"') do (
> >     echo Delete: %%a
> >     reg delete %%a /f
> >   )
> > )
> > ```
> 
> 感谢大佬！

这个可以用。

**Comment by mark88915** [comment]
> [Navicat16.2.3.zip](https://github.com/LiJunYi2/navicat-keygen-16V/files/11945536/Navicat16.2.3.zip) 按照教程

16.3.3 能用

**Comment by 866666** [comment]
您发给我的邮件已经被收到

**Comment by toor4nsn** [comment]
> 新版 (16.2.3) 的重置试用脚本如下
> 
> ```
> echo Delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Update
> reg delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Update /f
> echo Delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Registration[version and language]
> for /f %%i in ('"REG QUERY "HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium" /s | findstr /L Registration"') do (
>     reg delete %%i /va /f
> )
> 
> echo Delete Info and ShellFolder under HKEY_CURRENT_USER\Software\Classes\CLSID
> for /f "tokens=*" %%a in ('reg query "HKEY_CURRENT_USER\Software\Classes\CLSID"') do (
>   for /f "tokens=*" %%l in ('reg query "%%a" /f "Info" /s /e ^| findstr /i "Info"') do (
>     echo Delete: %%a
>     reg delete %%a /f
>   )
>   for /f "tokens=*" %%l in ('reg query "%%a" /f "ShellFolder" /s /e ^| findstr /i "ShellFolder"') do (
>     echo Delete: %%a
>     reg delete %%a /f
>   )
> )
> ```

WIN 16.3.3 依然有效 不愧是大佬

**Comment by he426100** [comment]
16.0升到16.3最新版，然后执行脚本，有用！

**Comment by 866666** [comment]
您发给我的邮件已经被收到

**Comment by huangsijun17** [comment]
![image](https://github.com/LiJunYi2/navicat-keygen-16V/assets/31504595/f08d5c47-8339-4e62-9fcc-617428c2757a)
怎么验证成功？

**Comment by JinBinPeng** [comment]
16.3.9激活成功

**Comment by 866666** [comment]
您发给我的邮件已经被收到

**Comment by 5201314IGNORE** [comment]
> 16.3.9激活成功

怎么激活的

**Comment by liuwei9829** [comment]
16.3.9成功激活，感谢

> [Navicat16.2.3.zip](https://github.com/LiJunYi2/navicat-keygen-16V/files/11945536/Navicat16.2.3.zip) 按照教程

**Comment by hayuoo** [comment]
我有以下报错，有人有遇到吗
![屏幕截图 2024-05-07 193300](https://github.com/LiJunYi2/navicat-keygen-16V/assets/92211433/98f2af9c-6fe0-49a9-8d64-5a6c9576717c)

**Comment by XiongJJ-XD** [comment]
16.0直接升级到16.3.9，已激活成功，非常感谢！

**Comment by ishiguang** [comment]
![CleanShot 2024-05-14 at 19 29 47@2x](https://github.com/LiJunYi2/navicat-keygen-16V/assets/8053835/ee3e4019-cf17-4076-ac91-d05180fb1997)

大佬，不能激活 32 位的么，我是在 pd 虚拟机，arm windows中安装的 32 位软件，因为 64 位安装不上，但是破解程序好像不支持 32 位的。

**Comment by huangsijun17** [comment]
> ![CleanShot 2024-05-14 at 19 29 47@2x](https://private-user-images.githubusercontent.com/8053835/330406304-ee3e4019-cf17-4076-ac91-d05180fb1997.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODczMTYsIm5iZiI6MTcxNTY4NzAxNiwicGF0aCI6Ii84MDUzODM1LzMzMDQwNjMwNC1lZTNlNDAxOS1jZjE3LTQwNzYtYWM5MS1kMDUxODBmYjE5OTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTRUMTE0MzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGY2ZmI2NGE0ZWJhNzE2MmE2ZWJmYmJlY2VhNDUwZmIyNzYxNzNjM2QzNWI0ZTcyNDExYWJiMWQ5ZWMwMjA3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3Ja7uiWYGiuRz2Tu-SN5IJWJSUdQYdFPB9AfxcsUV1o)
> 
> 大佬，不能激活 32 位的么，我是在 pd 虚拟机，arm windows中安装的 32 位软件，因为 64 位安装不上，但是破解程序好像不支持 32 位的。

关键不应该是ARM吗？

**Comment by ishiguang** [comment]
> > ![CleanShot 2024-05-14 at 19 29 47@2x](https://private-user-images.githubusercontent.com/8053835/330406304-ee3e4019-cf17-4076-ac91-d05180fb1997.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODczMTYsIm5iZiI6MTcxNTY4NzAxNiwicGF0aCI6Ii84MDUzODM1LzMzMDQwNjMwNC1lZTNlNDAxOS1jZjE3LTQwNzYtYWM5MS1kMDUxODBmYjE5OTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTRUMTE0MzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGY2ZmI2NGE0ZWJhNzE2MmE2ZWJmYmJlY2VhNDUwZmIyNzYxNzNjM2QzNWI0ZTcyNDExYWJiMWQ5ZWMwMjA3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3Ja7uiWYGiuRz2Tu-SN5IJWJSUdQYdFPB9AfxcsUV1o)
> > 大佬，不能激活 32 位的么，我是在 pd 虚拟机，arm windows中安装的 32 位软件，因为 64 位安装不上，但是破解程序好像不支持 32 位的。
> 
> 关键不应该是ARM吗？

arm windows安装的 x86 应用，是给模拟运行了吧？

**Comment by Ai-Yolo** [comment]
Navicat Premium 17好像也支持。
