### ISSUE TITLE
大佬,能否研究下navicat for redis

### ISSUE THREAD

**Issue by wenchen98** [LiJunYi2/navicat-keygen-16V#7]
![image](https://github.com/LiJunYi2/navicat-keygen-16V/assets/87108711/82db898b-7788-4211-92d0-5a869e0ab46a)
大佬,能否研究下navicat for redis

**Comment by LiJunYi2** [comment]
> ![image](https://github.com/LiJunYi2/navicat-keygen-16V/assets/87108711/82db898b-7788-4211-92d0-5a869e0ab46a)
> 
> 大佬,能否研究下navicat for redis

我尽力😂
